title: Marcelo's Portfolio
description: Marcelo Francisco da Silva Portfolio in GitHub Pages.
show_downloads: true
#google_analytics:
baseurl:

remote_theme: pages-themes/architect
plugins:
- jekyll-remote-theme
